"""<your message>

Revision ID: 307080a07b2e
Revises: 7b3479728f79
Create Date: 2023-08-14 11:50:29.422534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307080a07b2e'
down_revision = '7b3479728f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakery', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_baked_goods_bakery_id_bakeries', type_='foreignkey')
        batch_op.drop_column('bakery_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bakery_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_baked_goods_bakery_id_bakeries', 'bakeries', ['bakery_id'], ['id'])
        batch_op.drop_column('bakery')

    # ### end Alembic commands ###
